INSERT INTO `cmh`.`WORK_YEAR`(year) VALUES (2018);
INSERT INTO `cmh`.`WORK_YEAR`(year) VALUES (2019);
INSERT INTO `cmh`.`WORK_YEAR`(year) VALUES (2020);
INSERT INTO `cmh`.`WORK_YEAR`(year) VALUES (2021);
INSERT INTO `cmh`.`WORK_YEAR`(year) VALUES (2022);
INSERT INTO `cmh`.`WORK_YEAR`(year) VALUES (2023);
INSERT INTO `cmh`.`WORK_YEAR`(year) VALUES (2024);